name: Publish Android App
on:
  workflow_dispatch:
    inputs:
      build_number:
        description: 'Build number manually set'
        required: false
        type: number
      build_number_offset:
        description: 'Build number offset'
        required: true
        default: 123
        type: number
  push:
    branches: [main]
    
jobs:
  release-a:
    name: Build and release app
    runs-on: ubuntu-latest
    steps:
      - name: Calculate build number
        run: |
          if [[ -z $BUILD_NUMBER ]]; then
            echo "build number is not set."
            BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $OFFSET ))
          fi
          echo "BUILD_NUMBER=$BUILD_NUMBER" | tee -a $GITHUB_ENV
        env:
          OFFSET: ${{ github.event.inputs.build_number_offset || 123 }}
          BUILD_NUMBER: ${{ github.event.inputs.build_number }}

      - name: Build app
        run: echo "BUILD_NUMBER=$BUILD_NUMBER"

  release-b:
    name: Build and release app 2
    runs-on: ubuntu-latest
    needs: release-a
    steps:
      - name: Calculate build number
        run: |
          if [[ -z $BUILD_NUMBER ]]; then
            echo "build number is not set."
            BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $OFFSET ))
          fi
          echo "BUILD_NUMBER=$BUILD_NUMBER" | tee -a $GITHUB_ENV
        env:
          OFFSET: ${{ github.event.inputs.build_number_offset || 123 }}
          BUILD_NUMBER: ${{ github.event.inputs.build_number }}

      - name: Build app
        run: echo "BUILD_NUMBER=$BUILD_NUMBER"
